"""Ajout champ facebook_stats dans Lead

Revision ID: 2347601bfb52
Revises: 91dbcbf8df13
Create Date: 2025-06-28 00:12:16.331323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2347601bfb52'
down_revision = '91dbcbf8df13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facebook_stats', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_column('facebook_stats')

    # ### end Alembic commands ###
